Skip to content
Kinmla
clickgui-mod
Repository navigation
Code
Issues
Pull requests
Actions
Projects
Wiki
Security and quality
Insights
Settings
Build mod
Update build.yml #3
All jobs
Run details
Annotations
1 error, 2 warnings, and 1 notice
build
failed 1 minute ago in 31s
Search logs
2s
0s
1s
2s
23s
Run gradle wrapper --gradle-version 8.13

Welcome to Gradle 8.13!

Here are the highlights of this release:
 - Daemon JVM auto-provisioning
 - Enhancements for Scala plugin and JUnit testing
 - Improvements for build authors and plugin developers

For more details see https://docs.gradle.org/8.13/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
Fabric Loom: 1.9.2

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'clickgui-mod'.
> Failed to setup Minecraft, java.lang.UnsupportedOperationException: Unsupported unpick version

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 21s
Error: Process completed with exit code 1.
0s
0s
0s
0s
0s
 
