name: Build mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:8.10-jdk21
    defaults:
      run:
        working-directory: clickgui-mod
    steps:
      - uses: actions/checkout@v4

      - name: Generate Gradle wrapper
        run: gradle wrapper --gradle-version 8.10

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: clickgui-mod-jar
          path: clickgui-mod/build/libs/*.jar
